# User configurations for FKW_detector
# Mess with these parameters to change operation variables

# Where should the detector look for .dat audio files?
base_audio_directory: "2024_descent"  #2024_descent/240930/WISPR_000000_000000.dat

# Analyst Parameters
# How many audio files should be processed?
num_files_to_analyze: 30


